# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'UAKitBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'UAKit', :path => '../../'
  # Pods for UAKitBase
  pod 'SnapKit', '5.0.1'
  pod 'URLNavigator', '2.3.0'
#  pod 'lottie-ios', '3.1.6'
  pod 'SVGAPlayer', '2.3'
  pod 'SDWebImage', '5.5.2'
end
